### ISSUE TITLE
docker-compose up -d でエラー

### ISSUE THREAD

**Issue by ssaattww** [ibis-ssl/crane#472]
# バージョン

```bash
ibis@ibis-bd790i:~/ibis_ws/src/crane/docker$ docker-compose -v
docker-compose version 1.29.2, build unknown
```

# メッセージ
```bash
ibis@ibis-bd790i:~/ibis_ws/src/crane/docker$ docker-compose up -d
Creating network "docker_default" with the default driver
Creating docker_voicevox_1 ... 
Creating docker_ssl-vision-client_1 ... 
Creating docker_ssl-remote-control_1 ... 
Creating docker_ssl-game-controller_1 ... 

ERROR: for docker_ssl-game-controller_1  "host" network_mode is incompatible with port_bindings
Creating docker_voicevox_1            ... done
ERROR: for docker_ssl-vision-client_1  "host" network_mode is incompatible with port_bindings

ERROR: for docker_ssl-remote-control_1  "host" network_mode is incompatible with port_bindings

ERROR: for ssl-game-controller  "host" network_mode is incompatible with port_bindings

ERROR: for ssl-vision-client  "host" network_mode is incompatible with port_bindings

ERROR: for ssl-remote-control  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 679, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 559, in execute_convergence_plan
    return self._execute_convergence_create(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 473, in _execute_convergence_create
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 478, in <lambda>
    lambda service_name: create_and_start(self, service_name.number),
  File "/usr/lib/python3/dist-packages/compose/service.py", line 457, in create_and_start
    container = service.create_container(number=n, quiet=True)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 330, in create_container
    container_options = self._get_container_create_options(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 939, in _get_container_create_options
    container_options['host_config'] = self._get_container_host_config(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1014, in _get_container_host_config
    return self.client.create_host_config(
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 596, in create_host_config
    return HostConfig(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/types/containers.py", line 336, in __init__
    raise host_config_incompatible_error(
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings


```

**Comment by ssaattww** [comment]
ググると、これ出てくるけど結構昔の話だし、別のPCでは以前うまく行っていた気がするのだけどなぁ・・・
https://stackoverflow.com/questions/67819391/docker-compose-network-mode-and-port-binding-compatibility-issue

**Comment by HansRobo** [comment]
ここに書いてあるやつだと思う。

> ※docker-compose v1系はv1.2.5以降だとエラーが出て起動できないはず
https://ibis-ssl.github.io/ibis_documentation/ai/docker/#_1

手順に沿ってv2系をインストールして使うと直るはず

**Comment by ssaattww** [comment]
なるほど、2系だったらエラー出ないのか。試して見ます

**Comment by HansRobo** [comment]
練習会でv2系を使っていて大丈夫そうだったのでクローズします
